// This file is auto-generated by php artisan app:generate-enums. Do not edit directly.

export enum OrgUnitPermissionName {
    ViewOrgDashboard = 'view_org_dashboard',
    AddTenantMember = 'add_tenant_member',
    InviteExternalMember = 'invite_external_member',
    UpdateMember = 'update_member',
    RemoveMember = 'remove_member',
    CreateCustomers = 'create_customers',
    ViewCustomers = 'view_customers',
    UpdateCustomers = 'update_customers',
    DeleteCustomers = 'delete_customers',
    CreateIoTDevices = 'create_iot_devices',
    ViewIoTDevices = 'view_iot_devices',
    UpdateIoTDevices = 'update_iot_devices',
    DeleteIoTDevices = 'delete_iot_devices',
}

export enum OrgUnitRoleName {
    Admin = 'admin',
    Manager = 'manager',
    Technician = 'technician',
    Viewer = 'viewer',
}

export enum OrganisationUnitType {
    BRANCH = 'branch',
    DEPARTMENT = 'department',
    TEAM = 'team',
    OTHER = 'other',
}

export enum TenantPermissionName {
    UpdateTenantDetails = 'update_tenant_details',
    DeleteTenant = 'delete_tenant',
    CreateOrganisationUnits = 'create_organisation_units',
    ViewOrganisationUnits = 'view_organisation_units',
    UpdateOrganisationUnits = 'update_organisation_units',
    DeleteOrganisationUnits = 'delete_organisation_units',
    CreateOrgUnitRoles = 'create_org_unit_roles',
    ViewOrgUnitRoles = 'view_org_unit_roles',
    UpdateOrgUnitRoles = 'update_org_unit_roles',
    DeleteOrgUnitRoles = 'delete_org_unit_roles',
    CreateTenantRoles = 'create_tenant_roles',
    ViewTenantRoles = 'view_tenant_roles',
    EditTenantRoles = 'edit_tenant_roles',
    ViewTenantMembers = 'view_tenant_members',
    InviteTenantMembers = 'invite_tenant_members',
    UpdateTenantMembers = 'update_tenant_members',
    DeleteTenantMembers = 'delete_tenant_members',
    ViewBillingInformation = 'view_billing_information',
    EditBillingInformation = 'edit_billing_information',
}

export enum TenantRoleName {
    Admin = 'admin',
    Manager = 'manager',
    Finance = 'finance',
}

