FROM certbot/certbot:latest

# Copy your renewal script
COPY scripts/certbot_renew.sh /certbot_renew.sh
RUN chmod +x /certbot_renew.sh

# Add cron job: run every day at 2am
RUN echo "0 2 * * * root /certbot_renew.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/certbot-renew

# Give execution rights on the cron job
RUN chmod 0644 /etc/crontabs/certbot-renew

# Apply cron job
RUN crontab /etc/crontabs/certbot-renew

COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Start cron in the foreground
CMD ["crond", "-f"]