FROM nginx:alpine

COPY conf.d/*.template /etc/nginx/templates/

# Copy entrypoint script into the image
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

# Copy SSL-certificate polling script into image
COPY scripts/polling.sh /usr/local/bin/polling.sh

# Make sure it's executable
RUN chmod +x /usr/local/bin/entrypoint.sh /usr/local/bin/polling.sh

# Use the script as the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]