<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use ReflectionClass;

class GenerateTypeScriptEnums extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:generate-enums';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate TypeScript enums from PHP enums';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $enumsDir = app_path('Enums');
        $outputFile = resource_path('js/types/enums.ts');

        if (!File::exists($enumsDir)) {
            $this->error('Enums directory not found: ' . $enumsDir);
            return;
        }

        $files = File::files($enumsDir);
        $content = "// This file is auto-generated by php artisan app:generate-enums. Do not edit directly.\n\n";

        foreach ($files as $file) {
            $className = 'App\\Enums\\' . $file->getBasename('.php');
            
            if (!class_exists($className)) {
                continue;
            }

            $reflection = new ReflectionClass($className);
            
            if (!$reflection->isEnum()) {
                continue;
            }

            $enumName = $reflection->getShortName();
            $content .= "export enum {$enumName} {\n";

            foreach ($className::cases() as $case) {
                $value = is_string($case->value) ? "'{$case->value}'" : $case->value;
                $content .= "    {$case->name} = {$value},\n";
            }

            $content .= "}\n\n";
        }

        File::put($outputFile, $content);

        $this->info('TypeScript enums generated successfully at: ' . $outputFile);
    }
}
