---
- name: Prepare server directory structure for running images
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER')  }}"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "/home/{{ docker_user  }}/secrets"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0755'

    - name: Copy secrets directory to docker user context
      ansible.builtin.copy:
        src: "../../../../website/docker/secrets/"
        dest: "/home/{{ docker_user  }}/secrets/"
        mode: '0400'
      become_user: "{{ docker_user }}"
