services:
  # Laravel Application
  app:
    image: ${IMAGE_REPO}:laravel-app.latest
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ${ENV_FILE}:/var/www/.env     # Bind mount: Application environment variables
      - ${APP_FILES_DIR}:/var/www     # Volume or Bind mount: Application files to be served by nginx
    environment:
      MYSQL_ATTR_SSL_CA: /run/secrets/mysql_app_db_ssl
    secrets:
      - mysql_app_db_database
      - mysql_app_db_username
      - mysql_app_db_password
      - mysql_app_db_ssl
      - mysql_testing_db_database
      - mysql_testing_db_username
      - mysql_testing_db_password
      - redis_password
    depends_on: 
      redis:
        condition: service_started
    command: ["/bin/sh", "-c", ". /usr/local/bin/read-db-credentials.sh; . /usr/local/bin/read-db-credentials-testing.sh; . /usr/local/bin/read-redis-password.sh; exec php-fpm"]
    profiles: ["all", "dev-bindmount", "dev-volume", "testing", "staging", "production"]

  # Nginx Web Server
  nginx:
    image: ${IMAGE_REPO}:website-nginx.latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ${APP_FILES_DIR}:/var/www           # Volume or Bind mount: Application files to be served by nginx
      - certbot_files:/var/www/certbot/:ro  # Volume: Certbot files to be served by nginx (for confirming domain ownership)
      - ./secrets/letsencrypt:/etc/letsencrypt/:ro    # Volume: Https certificates from certs container
    depends_on:
      app:
        condition: service_started
        required: false
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    profiles: ["all", "dev-bindmount", "dev-volume", "testing", "staging", "production"]

  # Redis for sessions and caching
  redis:
    image: ${IMAGE_REPO}:website-redis.latest
    container_name: redis
    restart: unless-stopped
    secrets:
      - redis_password
    environment:
      REDIS_PASS_FILE: /run/secrets/redis_password
    profiles: ["all", "dev-bindmount", "dev-volume", "testing", "staging", "production"]

  # Certbot for generating real SSL certificates
  certbot:
    image: ${IMAGE_REPO}:website-certbot.latest
    container_name: certbot
    depends_on:
      - nginx
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL}
    restart: no
    volumes:
      - certbot_files:/var/www/certbot/:rw # Volume: Certbot files to be served by nginx (for confirming domain ownership)
      - ./secrets/letsencrypt:/etc/letsencrypt/:rw # Volume: Https certificates from Certbot
    profiles: ["all", "staging", "production"]

volumes:
  app_files:
  certbot_files:
  certbot_certs:

secrets:
  mysql_testing_db_password:
    file: ./secrets/mysql_testing_db_password
  mysql_testing_db_username:
    file: ./secrets/mysql_testing_db_username
  mysql_testing_db_database:
    file: ./secrets/mysql_testing_db_database
  mysql_app_db_password:
    file: ./secrets/mysql_app_db_password
  mysql_app_db_username:
    file: ./secrets/mysql_app_db_username
  mysql_app_db_database:
    file: ./secrets/mysql_app_db_database
  mysql_app_db_ssl:
    file: ./secrets/mysql_app_db_ssl
  mysql_app_db_port:
    file: ./secrets/mysql_app_db_port
  mysql_app_db_host:
    file: ./secrets/mysql_app_db_host
  mysql_db_rootpass:
    file: ./secrets/mysql_db_rootpass
  redis_password:
    file: ./secrets/redis_password