name: Create kickstarting resources
description: Create or destroy ephemeral Terraform infrastructure

inputs:
  destroy:
    description: "create or destroy"
    required: true
    default: "false"

outputs:
  spaces_access_id:
    description: "Spaces access key ID"
    value: ${{ steps.outputs.outputs.spaces_access_id }}
  spaces_secret_key:
    description: "Spaces secret key"
    value: ${{ steps.outputs.outputs.spaces_secret_key }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - uses: actions/download-artifact@v4
      with:
        name: backend.hcl
        path: deployment/terraform/ephemeral

    - shell: bash
      run: |
        terraform -chdir=spaces-key init -backend-config="../backend.hcl" -backend-config="workspace_key_prefix=projects/${{ github.event.repository.name }}/infra-ephemeral"
        terraform -chdir=spaces-key workspace select -or-create spaces-key

    - shell: bash
      if: ${{ inputs.destroy == "true" }}
      run: |
        if [ "${{ inputs.destroy }}" = "true" ]; then
          terraform -chdir=deployment/terraform/ephemeral/spaces-key apply -destroy -auto-approve
        else
          terraform -chdir=deployment/terraform/ephemeral/spaces-key apply -auto-approve
        fi

    - name: Capture outputs
      id: outputs
      shell: bash
      run: |
        if [ "${{ inputs.destroy }}" = "true" ]; then
          echo "spaces_access_id=" >> $GITHUB_OUTPUT
          echo "spaces_secret_key=" >> $GITHUB_OUTPUT
        else
          echo "spaces_access_id=$(terraform -chdir=deployment/terraform/ephemeral/spaces-key output -raw spaces_access_id)" >> $GITHUB_OUTPUT
          echo "spaces_secret_key=$(terraform -chdir=deployment/terraform/ephemeral/spaces-key output -raw spaces_secret_key)" >> $GITHUB_OUTPUT
        fi