name: Install Docker
description: Set up SSH connection and create dedicated docker user

inputs:
  default_path:
    description: "Ansible path"
    required: false
    default: "deployment/ansible"

  ssh_private_key:
    description: "The private SSH key"
    required: true

runs:
  using: composite
  steps:
  - name: Start ssh-agent and add private key
    uses: webfactory/ssh-agent@v0.9.0
    with:
      ssh-private-key: ${{ inputs.ssh_private_key }}

  - shell: bash
    run: |
      mkdir -p ~/.ssh
      ssh-keyscan -H "$DROPLET_IP" >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts          

  - shell: bash
    run: |
      sudo apt update
      sudo apt install -y ansible

  - shell: bash
    working-directory: ${{ inputs.default_path }}
    run: |
      ansible-playbook playbooks/docker/deploy.yml