---
- name: Deploy Docker images with Github Actions
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER')  }}"
    root: "{{ lookup('env', 'WORKSPACE') }}"
    environment_suffix: "{{ lookup('env', 'ENVIRONMENT') }}"

  tasks:
    - name: Get docker user UID
      ansible.builtin.command: id -u {{ docker_user }}
      register: docker_uid
      changed_when: false

    - name: Check if stop_env.sh exists
      stat:
        path: "/home/{{ docker_user  }}/stop_env.sh"
      register: stop_env

    - name: Take down any containers using existing docker-compose.yml
      shell:
        chdir: /home/{{ docker_user }}
        cmd: ./stop_env.sh production
      become_user: "{{ docker_user }}"
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ docker_uid.stdout }}"
        DOCKER_HOST: "unix:///run/user/{{ docker_uid.stdout }}/docker.sock"
      changed_when: false
      when: stop_env.stat.exists

    - name: Copy *.sh files and add execution permissions
      copy:
        src: "{{ root  }}/website/{{ item }}"
        dest: "/home/{{ docker_user  }}/{{ item }}"
        mode: a+x
      loop:
        - run_env.sh
        - stop_env.sh
      become_user: "{{ docker_user  }}"

    - name: Copy docker files
      copy:
        src: "{{ root  }}/website/docker/{{ item }}"
        dest: "/home/{{ docker_user  }}/{{ item }}"
      loop:
        - ".env.{{ environment_suffix  }}"
        - docker-compose.yml
      become_user: "{{ docker_user  }}"

    - name: Copy laravel environment file
      copy:
        src: "{{ root  }}/website/docker/img_laravel/.env"
        dest: "/home/{{ docker_user  }}/.env"
      become_user: "{{ docker_user  }}"

    - name: Find all `secrets` files
      ansible.builtin.find:
        paths: ./secrets
        file_type: file
      register: secret_files

    - name: Ensure secret files are readable by the docker container
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ docker_user  }}"
        group: "{{ docker_user  }}"
        mode: "0644"
      loop: "{{ secret_files.files }}"

    # - name: Deploy images
    #   shell:
    #     chdir: /home/{{ docker_user }}
    #     cmd: ./run_env.sh
    #   become_user: "{{ docker_user }}"
    #   environment:
    #     XDG_RUNTIME_DIR: "/run/user/{{ docker_uid.stdout }}"
    #     DOCKER_HOST: "unix:///run/user/{{ docker_uid.stdout }}/docker.sock"
    #   changed_when: false
