#################################################
###                                           ###
###   PHP / Laravel Stage.                    ###
###                                           ###
#################################################
# Docker Official Image: php:8.3-fpm. Jan 17, 2026 at 3:57 am
FROM php@sha256:37ab5e71c4f064723cef73abe87a52e1cc10d116da88f26a08444cd3fdbd75a0

ARG WWW_UID=82
ARG WWW_GID=82

# --- Dependencies --- #

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    # Used by composer and laravel to make HTTP requests
    curl \
    # Handling .zip archives. Used by composer
    zip \
    unzip \
    # Enable image processing features. Used by laravels intervention/image package`
    libpng-dev \
    libjpeg-dev \
    # Node.js and npm for frontend assets
    nodejs \
    npm \
    # mysql-client for testrunning pipeline. Used by clone_db_for_testing.sh
    default-mysql-client

# Laravels database drivers for MariaDB/mySQL and bcmath for laravel-lang
RUN docker-php-ext-install pdo pdo_mysql bcmath

# Install Redis extension
RUN pecl install redis && docker-php-ext-enable redis

# Install Vite globally for testing builds in container
RUN npm install -g vite

# Get latest Composer for project php dependencies
# Docker Official Image: composer:latest. Jan 17, 2026 at 6:13 am
COPY --from=composer@sha256:ce78434db8122b0c3b0ec2056da0072551780d60e864943008c3f5a785db0900 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# --- Users and Groups --- #

# Set group ID and user ID for www-data user to 82. This user runs the laravel application
RUN usermod -u ${WWW_UID} www-data && groupmod -g ${WWW_GID} www-data

# Add a testrunner user and group for running the db cloning script
RUN addgroup -g 1002 testrunner && \
    adduser -u 1002 -D -S -G testrunner -s /bin/bash testrunner

# Create shared group for files/scripts used by both www-data user and testrunner user
RUN addgroup -g 1003 shared && \
    addgroup www-data shared && \
    addgroup testrunner shared

# Set ownership of the working directory to www user
RUN chown -R www-data:www-data /var/www

# Expose port 9000
EXPOSE 9000



# --- Scripts for loading in Docker secrets and cloning/testing the laravel database --- #

ARG DOCKERFILE_DIR=docker/img_laravel

# Copy scripts
COPY ${DOCKERFILE_DIR}/scripts/*.sh /usr/local/bin/

# Set permissions (Preserving original logic)
RUN chown root:www-data         /usr/local/bin/read-db-credentials.sh           && chmod 550 /usr/local/bin/read-db-credentials.sh && \
    chown root:www-data         /usr/local/bin/test.sh                          && chmod 550 /usr/local/bin/test.sh && \
    chown root:shared           /usr/local/bin/read-redis-password.sh           && chmod 550 /usr/local/bin/read-redis-password.sh && \
    chown root:shared           /usr/local/bin/read-db-credentials-testing.sh   && chmod 550 /usr/local/bin/read-db-credentials-testing.sh && \
    chown root:testrunner       /usr/local/bin/test_cloned_db.sh                && chmod 550 /usr/local/bin/test_cloned_db.sh && \
    chown root:testrunner       /usr/local/bin/clone_db_for_testing.sh          && chmod 550 /usr/local/bin/clone_db_for_testing.sh
