ARG BASE_IMAGE=local/starterkit.laravel-react-docker:laravel-base.latest

#################################################
###                                           ###
###   Node / front-end build stage.           ###
###                                           ###
#################################################
# Docker Official Image: node:20. Jan 15, 2026 at 2:38 am
FROM node@sha256:3680462e16df266d30b103a3e38e2bc315bf917d0ab873fbddbee437bf0bd2d0

# Set working directory
WORKDIR /var/www

# Copy package.json and package-lock.json for building js dependencies
COPY laravel_root/package.json laravel_root/package-lock.json ./
COPY laravel_root/vite.config.* ./

# Install npm dependencies
RUN npm ci

# Copy the entire resources directory for the build
COPY laravel_root/resources ./resources

# Install npm dependencies
RUN npm install


#################################################
###                                           ###
###   Laravel / back-end build stage.         ###
###                                           ###
#################################################
FROM ${BASE_IMAGE}

# Switch to www user
USER www-data

# Copy composer files
COPY --chown=www-data:www-data laravel_root/composer.json laravel_root/composer.lock ./

# Install composer dependencies without running scripts
RUN composer install --no-scripts

# Copy node_modules from the Node stage
COPY --chown=www-data:www-data --from=0 /var/www/node_modules ./node_modules

# Copy the Laravel application files(.dockerignore ignores the node_modules, public/build and vendorfolders)
COPY --chown=www-data:www-data laravel_root/ .

# Run composer scripts after all files are in place
RUN composer run-script post-autoload-dump

# Build main app assets into the public folder (currently using vite)
RUN npm run build

# Give testrunner full access to the logs
RUN chown -R www-data:shared /var/www/storage/logs \
    && chmod -R 770 /var/www/storage/logs
# Give testrunner full access to compiled blade views
RUN chown -R www-data:shared /var/www/storage/framework/views \
    && chmod -R 770 /var/www/storage/framework/views


