name: Push changes

on:
  push:
    branches:
      - staging
      - dev
      - production

  workflow_dispatch:
    inputs:
      environment:
        description: 'Push changes'
        required: true
        type: choice
        options:
          - staging
          - dev
          - production

env:
  ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment || github.ref_name) || github.ref_name }}
  TAG_ADDITION: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment || github.ref_name) || github.ref_name }}
  IMAGE_REPO: ${{ vars.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build-images:
    name: Build and Push All Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Docker Tags
        id: vars
        uses: ./.github/actions/docker-tag
        with:
          branch_name: ${{ github.ref_name }}
          docker_username: ${{ vars.DOCKER_HUB_USERNAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push with Docker Bake
        uses: docker/bake-action@v3
        with:
          workdir: website
          push: true
          files: |
            docker/docker-compose.yml
          targets: app, scheduler, nginx, redis, certbot
          set: |
            *.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:bake-cache.${{ steps.vars.outputs.safe_tag }}
            *.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:bake-cache.main
            *.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:bake-cache.${{ steps.vars.outputs.safe_tag }},mode=max
            app.target=${{ env.ENVIRONMENT == 'dev' && 'volume-dev' || 'volume-prod' }}
            *.image=${{ steps.vars.outputs.image_repo }}:${{ env.TAG_ADDITION }}

  deploy-builds:
    runs-on: ubuntu-latest
    needs: [build-images]
    env:
      DOCKER_USER: docker-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/terraform/utils/generate-backend
        with:
          state_bucket_region: ${{ vars.DO_STATE_BUCKET_REGION }}
          state_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      - uses: ./.github/actions/terraform/utils/state
        id: outputs
        env:
          # DigitalOcean Spaces bucket name and access key, used for terraform remote state.
          AWS_ACCESS_KEY_ID: ${{ vars.DO_STATE_BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_STATE_BUCKET_SECRET_KEY }}
        with:
          output_keys: "droplet_ipv4"
          working_dir: deployment/terraform/environments/common
          workspace_key_prefix: "projects/${{ github.event.repository.name }}/infra-environments"
          environment: ${{ env.ENVIRONMENT }} # Use current environment as workspace for terraform

      - uses: ./.github/actions/ansible/deploy-builds
        env:
          DROPLET_IP: ${{ fromJSON(steps.outputs.outputs.json).droplet_ipv4 }}
          ANSIBLE_HOST_KEY_CHECKING: "True"
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
          WORKSPACE: ${{ github.workspace }} # Required in ansible step for finding files in repo
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}