name: Run tests locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TAG_ADDITION: test
  RUN_ID: ${{ github.run_id }}

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate Docker Tags
        id: vars
        uses: ./.github/actions/docker-tag
        with:
          branch_name: ${{ github.head_ref || github.ref_name }}
          docker_username: ${{ vars.DOCKER_HUB_USERNAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Load environment variables
        run: |
          set -o allexport
          source website/docker/.env.local
          set +o allexport

      - name: Build and Load with Docker Bake
        uses: docker/bake-action@v7
        with:
          push: false
          load: true
          source: ./website
          files: |
            compose.yml
            compose.dev.yaml
          targets: |
            app
            scheduler
            nginx
            redis
            mysql_db
            cert_local
          set: |
            app.target=volume-dev
            scheduler.args.SCHEDULER_BASE=volume-dev

            app.tags=${{ steps.vars.outputs.image_repo }}:laravel-app.${{ env.RUN_ID }}
            scheduler.tags=${{ steps.vars.outputs.image_repo }}:laravel-scheduler.${{ env.RUN_ID }}
            nginx.tags=${{ steps.vars.outputs.image_repo }}:website-nginx.${{ env.RUN_ID }}
            redis.tags=${{ steps.vars.outputs.image_repo }}:website-redis.${{ env.RUN_ID }}
            mysql_db.tags=${{ steps.vars.outputs.image_repo }}:mysql-db.${{ env.RUN_ID }}
            cert_local.tags=${{ steps.vars.outputs.image_repo }}:cert-local.${{ env.RUN_ID }}

            app.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-app.${{ steps.vars.outputs.safe_tag }}.cache
            app.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-app.main.cache
            app.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-app.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

            scheduler.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-scheduler.${{ steps.vars.outputs.safe_tag }}.cache
            scheduler.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-scheduler.main.cache
            scheduler.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:laravel-scheduler.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

            nginx.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-nginx.${{ steps.vars.outputs.safe_tag }}.cache
            nginx.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-nginx.main.cache
            nginx.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-nginx.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

            redis.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-redis.${{ steps.vars.outputs.safe_tag }}.cache
            redis.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-redis.main.cache
            redis.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:website-redis.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

            mysql_db.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:mysql-db.${{ steps.vars.outputs.safe_tag }}.cache
            mysql_db.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:mysql-db.main.cache
            mysql_db.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:mysql-db.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

            cert_local.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:cert-local.${{ steps.vars.outputs.safe_tag }}.cache
            cert_local.cache-from=type=registry,ref=${{ steps.vars.outputs.image_repo }}:cert-local.main.cache
            cert_local.cache-to=type=registry,ref=${{ steps.vars.outputs.image_repo }}:cert-local.${{ steps.vars.outputs.safe_tag }}.cache,mode=max

      - name: Start Docker services to mock production
        working-directory: website
        env:
          TAG_ADDITION: ${{ env.RUN_ID }}
          IMAGE_REPO: ${{ steps.vars.outputs.image_repo }}
        run: |
          docker compose -f docker-compose.yml --env-file docker/.env.mock-prod --profile mock-prod up -d --no-build

      - name: Run Laravel tests on mock production in parallel
        run: |
          docker exec -u www-data laravel_app sh -c 'bash /usr/local/bin/test.sh --parallel'

      - name: Run PHPStan
        run: |
          docker run --rm \
            ${{ steps.vars.outputs.image_repo }}:laravel-app.${{ env.RUN_ID }} \
            php vendor/bin/phpstan analyse --memory-limit=2G
 
      - name: Run Architecture Tests
        run: |
          docker run --rm \
            ${{ steps.vars.outputs.image_repo }}:laravel-app.${{ env.RUN_ID }} \
            php vendor/bin/pest tests/Architecture
